ALTER TABLE `status` ADD COLUMN `final_url` VARCHAR(512) DEFAULT NULL;
ALTER TABLE `history` ADD COLUMN `final_url` VARCHAR(512) DEFAULT NULL;
ALTER TABLE `url` ADD COLUMN `exclude_checking` BOOLEAN DEFAULT NULL;